version: '2'
services:
  frontend:
    image: aghost7/herman-github
    ports:
      - 4567
    environment:
      - HERMAN_GH_SECRET
    volumes:
      - ./config:/etc/herman
  backend:
    image: aghost7/herman-git
    environment:
      - DOCKER_USERNAME
      - DOCKER_PASSWORD
    volumes:
      - ./config:/etc/herman
  rabbitmq:
    image: rabbitmq
