version: '2'
services:
  frontend:
    image: aghost7/herman-github
    ports:
      - 4567:4567
    environment:
      - HERMAN_GH_SECRET
    volumes:
      - ./config:/etc/herman:ro
    depends_on:
      - rabbitmq
  backend:
    image: aghost7/herman-git
    environment:
      - DOCKER_USERNAME
      - DOCKER_PASSWORD
    privileged: true
    volumes:
      - ./config:/etc/herman:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq
