amqp:
  url: 'amqp://rabbitmq'
github:
  port: 4567
  secret: ${HERMAN_GH_SECRET}
  images:
    - url: git@github.com:AGhost-7/herman.git
      name: aghost7/herman-git
      path: packages/herman-git
    - url: git@github.com:AGhost-7/herman.git
      name: aghost7/herman-github
      path: packages/herman-github
git:
  dir: /var/lib/herman/git
